security:
    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
#        Big\ElibreBundle\Entity\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
          chain:
#            providers: [in_memory, user_db]
            providers: [in_memory, fos_user_db]
#            providers: [in_memory, fos_user_db_mod]
      
        in_memory:
            memory:
                users:
                    #user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
#        user_db:
#            entity: { class: Big\ElibreBundle\Entity\User, property: username }
        fos_user_db:
            id: fos_user.user_provider.username
#        fos_user_db_mod:
#            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        login:
#            pattern:  ^/login$
#            security: false

        main:
            pattern:    ^/
            form_login:
                provider: fos_user_db
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
#            form_login:
#                check_path: login_check
#                login_path: login
#            logout:
#                path:   logout
##                target: _demo
#            anonymous: true
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
#        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*/download$, roles: ROLE_USER }
        - { path: ^/adm/test$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/adm/.*$, roles: ROLE_ADMIN }
        
       
